import {create} from "zustand";
import {persist} from "zustand/middleware";
import type {FinishedGame,GameState,Player} from "@/lib/types";
import {activeRounds,makePlayers,totals,uuid} from "@/lib/utils";
const now=()=>new Date().toISOString();
const blank=():GameState=>({gameId:"",gameName:"",players:makePlayers(2),rounds:[],starterId:"p1",targetScore:500,status:"setup",updatedAt:now()});
type Sync="local"|"dirty"|"saving"|"saved"|"loading"|"error";
type Store={game:GameState;history:FinishedGame[];closedBy:string;syncStatus:Sync;createGame:(p:{name:string;players:Player[];targetScore:number})=>void;toggleStarter:()=>void;setClosedBy:(id:string)=>void;addRound:(scores:Record<string,number>)=>void;addPenalty:(id:string)=>void;undo:()=>void;editRound:(id:string)=>Record<string,number>|null;resetGame:()=>void;rematch:()=>void;newSetup:()=>void;saveCloud:()=>Promise<void>;loadCloud:()=>Promise<void>};
function finish(game:GameState){if(game.status==="finished")return game;const t=totals(game);if(!game.players.some(p=>(t[p.id]??0)>=game.targetScore))return game;let w=game.players[0];game.players.forEach(p=>{if((t[p.id]??0)>(t[w.id]??0))w=p});return {...game,status:"finished" as const,winnerId:w.id,updatedAt:now()}}
function addHistory(game:GameState,h:FinishedGame[]){if(game.status!=="finished"||!game.winnerId||h.some(x=>x.gameId===game.gameId))return h;const t=totals(game),w=game.players.find(p=>p.id===game.winnerId);return[{gameId:game.gameId,gameName:game.gameName,winnerName:w?.name??"Winner",targetScore:game.targetScore,rounds:activeRounds(game.rounds).length,totals:t,finishedAt:now()},...h].slice(0,50)}
export const useGameStore=create<Store>()(persist((set,get)=>({game:blank(),history:[],closedBy:"",syncStatus:"local",
createGame:({name,players,targetScore})=>set({game:{gameId:uuid(),gameName:name||`Game ${new Date().toLocaleDateString()}`,players,rounds:[],starterId:players[0]?.id??"p1",targetScore,status:"active",updatedAt:now()},closedBy:"",syncStatus:"dirty"}),
toggleStarter:()=>set(s=>{if(activeRounds(s.game.rounds).length)return s;const i=s.game.players.findIndex(p=>p.id===s.game.starterId);return{game:{...s.game,starterId:s.game.players[(i+1)%s.game.players.length].id,updatedAt:now()},syncStatus:"dirty"}}),
setClosedBy:id=>set(s=>({closedBy:s.closedBy===id?"":id})),
addRound:scores=>set(s=>{if(!s.game.gameId||s.game.status==="finished")return s;const next={...scores};if(s.closedBy)next[s.closedBy]=Number(next[s.closedBy]??0)+15;if(!Object.values(next).some(v=>Number(v)!==0)&&!s.closedBy)return s;const i=activeRounds(s.game.rounds).length,si=s.game.players.findIndex(p=>p.id===s.game.starterId);const round={id:uuid(),scores:next,closedBy:s.closedBy||undefined,starterId:s.game.players[(Math.max(0,si)+i)%s.game.players.length].id,createdAt:now(),type:"round" as const};const game=finish({...s.game,rounds:[...s.game.rounds,round],updatedAt:now()});return{game,history:addHistory(game,s.history),closedBy:"",syncStatus:"dirty"}}),
addPenalty:id=>set(s=>{if(!s.game.gameId||s.game.status==="finished")return s;const scores:Record<string,number>={};s.game.players.forEach(p=>scores[p.id]=p.id===id?-50:0);const i=activeRounds(s.game.rounds).length,si=s.game.players.findIndex(p=>p.id===s.game.starterId);const game=finish({...s.game,rounds:[...s.game.rounds,{id:uuid(),scores,starterId:s.game.players[(Math.max(0,si)+i)%s.game.players.length].id,createdAt:now(),type:"penalty"}],updatedAt:now()});return{game,history:addHistory(game,s.history),syncStatus:"dirty"}}),
undo:()=>set(s=>{const rounds=[...s.game.rounds];for(let i=rounds.length-1;i>=0;i--){if(!rounds[i].deletedAt){rounds[i]={...rounds[i],deletedAt:now()};break}}return{game:{...s.game,rounds,status:"active",winnerId:undefined,updatedAt:now()},syncStatus:"dirty"}}),
editRound:id=>{const s=get(),r=s.game.rounds.find(x=>x.id===id&&!x.deletedAt);if(!r)return null;set(st=>({game:{...st.game,rounds:st.game.rounds.map(x=>x.id===id?{...x,deletedAt:now()}:x),status:"active",winnerId:undefined,updatedAt:now()},closedBy:r.closedBy??"",syncStatus:"dirty"}));return r.scores},
resetGame:()=>set(s=>({game:{...s.game,rounds:s.game.rounds.map(r=>({...r,deletedAt:r.deletedAt??now()})),status:"active",winnerId:undefined,updatedAt:now()},syncStatus:"dirty"})),
rematch:()=>set(s=>({game:{...blank(),gameId:uuid(),gameName:"Rematch",players:s.game.players,starterId:s.game.players[0].id,targetScore:s.game.targetScore,status:"active"},closedBy:"",syncStatus:"dirty"})),
newSetup:()=>set({game:blank(),closedBy:"",syncStatus:"local"}),
saveCloud:async()=>{set({syncStatus:"saving"});try{localStorage.setItem("rummy500-cloud-last",JSON.stringify(get().game));set({syncStatus:"saved"})}catch{set({syncStatus:"error"})}},
loadCloud:async()=>{set({syncStatus:"loading"});try{const raw=localStorage.getItem("rummy500-cloud-last");if(raw)set({game:JSON.parse(raw),syncStatus:"saved"});else set({syncStatus:"local"})}catch{set({syncStatus:"error"})}}
}),{name:"rummy500-nextjs-store"}));
